version: "3.8"

services:
  db:
    image: postgres:16.0
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ocula
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  ocula:
    image: ocula:${APP_VERSION}
    build:
      context: "."
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.docker

volumes:
  pgdata:
  static:
