# Generated by Django 5.1 on 2024-08-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weatherapp", "0002_remove_temperature_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temperature",
            name="recorded_at",
            field=models.DateField(),
        ),
    ]
